---
- name: setup pam-gnupg
  blockinfile:
    dest: /etc/pam.d/{{ login_manager.0 }}
    content: |
      auth     optional  pam_gnupg.so store-only
      session  optional  pam_gnupg.so

  blockinfile:
    dest: /etc/pam.d/i3lock
    content: auth     optional  pam_gnupg.so

  copy:
    content: allow-preset-passphrase
    dest: /home/{{ ansible_user }}/.gnupg/gpg-agent.conf

  shell: gpg -K --with-keygrip | grep -oP 'Keygrip = \K.*' | tail -1 > /home/{{ ansible_user }}/.pam-gnupg
             
